### ISSUE TITLE
what are you doing trying to hit my environment

### ISSUE THREAD

**Issue by balq60** [inkdrop-org/inkdrop-visualizer#12]
See image.

If you say you are processing the plan, why did you try and hit my environment reading the plan?

![tryingtohitenv](https://github.com/inkdrop-org/inkdrop-visualizer/assets/26937958/a97e1e05-9ae0-4272-948a-5d2c8edd7d17)

**Comment by balq60** [comment]
This feels like a scam to get into folks environments.

**Comment by albschi** [comment]
Our code executes `terraform graph` and requires no credentials; nor does it read credentials from you. If `terraform graph` fails to run in your local environment, that is an issue on your end and is not related to Inkdrop.

My question is: Are we genuinely trying to be productive and solve issues here? The entire code is open source and you will find no place where we collect credentials.
